#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# For the reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

def generate(env):
    # Some stuff that improves build performance according to: https://github.com/SCons/scons/wiki/GoFastButton
    env.Decider("content-timestamp")
    env.SetOption("max_drift", 1)
    env.SetOption("implicit_cache", 1)

    # Enable C++20
    if env.get("is_msvc", False):
        env["CXXFLAGS"].remove("/std:c++17")
        env["CXXFLAGS"].insert(0, "/std:c++20")
        env["CXXFLAGS"].insert(0, "/Zc:preprocessor")
    else:
        env["CXXFLAGS"].remove("-std=c++17")
        env["CXXFLAGS"].insert(0, "-std=c++20")

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/", "src/tests"])

generate(env)

sources = Glob("src/*.cpp") + Glob("src/tests/*.cpp")

if env["target"] in ["editor", "template_debug"]:
    try:
        doc_data = env.GodotCPPDocData("src/gen/doc_data.gen.cpp", source=Glob("doc_classes/*.xml"))
        sources.append(doc_data)
        print("Class reference added.")
    except AttributeError:
        print("Not including class reference as we're targeting a pre-4.3 baseline.")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "game/bin/libgdsummator.{}.{}.framework/libgdsummator.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "game/bin/libgdsummator{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
